theme: jekyll-theme-cayman

# Google services
google_analytics: UA-161452755-1

title: Crisis Unite: Covid-19
description: If you're impacted by Covid-19, here's a list of resources to receive help, and to provide help.

# Build settings
plugins:
  - jekyll-seo-tag
