title: Crisis Community
url: 'https://crisiscommunity.com'
baseurl: null
google_analytics_key: UA-161452755-1
show_full_navigation: true
logo: /siteicon.png
description: >-
  A site that compiles verified methods of providing help and seeking help in
  time of crisis
author:
  name: Richard Lee
  email: me@zrlee.com
  twitter: ImRichardLee
social:
  name: null
  links: null
timezone: Etc/UTC
permalink: pretty
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENCE
collections:
  docs:
    title: Categories
    permalink: '/:path/'
    output: true
defaults:
  - scope:
      path: ''
    values:
      layout: default
  - scope:
      path: ''
      type: docs
    values:
      seo:
        type: Article
      _comments:
        category: Group navigation links with this field
        order: Used to sort links in the navigation
      _options:
        content:
          width: 800
          height: 2000
  - scope:
      path: ''
      type: posts
    values:
      _comments:
        type: Marks the impact of this release
types:
  - minor
  - major
